# Generated by Django 2.2.3 on 2019-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=32, verbose_name='材料'),
        ),
    ]
