# Generated by Django 2.2.3 on 2019-10-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0002_auto_20191011_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zr.Material'),
        ),
    ]
