# Generated by Django 2.2.3 on 2019-12-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0003_auto_20191011_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='E',
            field=models.CharField(default=1, max_length=128, verbose_name='弹性模量'),
        ),
        migrations.AddField(
            model_name='material',
            name='P',
            field=models.CharField(default=1, max_length=128, verbose_name='泊松比'),
        ),
        migrations.AddField(
            model_name='material',
            name='hot',
            field=models.CharField(default=1, max_length=128, verbose_name='导热系数'),
        ),
        migrations.AddField(
            model_name='material',
            name='midu',
            field=models.CharField(default=1, max_length=128, verbose_name='密度'),
        ),
        migrations.AddField(
            model_name='material',
            name='moca',
            field=models.CharField(default=1, max_length=128, verbose_name='摩擦系数'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=128, null=True, verbose_name='材料名称'),
        ),
    ]
