# Generated by Django 2.2.3 on 2020-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0005_auto_20200108_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品名称')),
                ('standard', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品标准')),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品国别')),
                ('C', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品含碳量(%)')),
                ('Si', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品含硅量(%)')),
                ('Mn', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品含锰量(%)')),
                ('P', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品含磷量(%)')),
                ('S', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品含硫量(%)')),
                ('Ys', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品屈服强度(Mpa)')),
                ('Rm', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品抗拉强度(Mpa)')),
                ('Akv', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='产品冲击功(J)')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
    ]
