# Generated by Django 2.2.3 on 2019-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190815_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, default='', upload_to='face/%Y/%m/%d'),
        ),
    ]
