# Generated by Django 2.2.3 on 2019-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_confirmnumber_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(default='', max_length=128, verbose_name='文件名'),
        ),
    ]
